### ISSUE TITLE
Improve WordPress gallery code

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#532] opened 2015-08-27 15:25 UTC
This should be more DRY and more calculated. Maybe this could even be removed or simplified.

Also, do not use `calc()`, since it's not supported well enough right now.

**Comment by luukdv** [comment] 2016-02-08 13:21
Close this one in favor of a component?

**Comment by haroldangenent** [comment] 2016-02-08 15:23
I think this should stay a part of TrendPress, because this is default WordPress behaviour.

**Comment by haroldangenent** [comment] 2016-02-17 18:34
No, `calc` is fine to use, if you're not dividing or multiplying.

**Comment by luukdv** [comment] 2016-02-18 13:02
Maybe use grid.

**Comment by luukdv** [comment] 2016-02-18 13:02
Don't support column choice.

**Comment by sboerrigter** [comment] 2016-03-17 15:56
Can we make it look like this?

![screen shot 2016-03-17 at 16 56 00](https://cloud.githubusercontent.com/assets/786875/13852150/2e7aea50-ec61-11e5-9e62-7d33261e1ebf.png)

**Comment by haroldangenent** [comment] 2016-05-09 13:47
- There seem to be four items next to eachother (opposed to the 6 in the screenshot)
- Five items would fit too, that would probably look better (using the grid would eliminate the need of a lot of code)
- Responsive is not that beautiful (using grid would make it better)
- When fitting five items, they don't fit by 10px. Using the grid would allow you to always fill the width of the content.
- Transition should probably be removed, since this would be the _only_ instance in the entire theme where transition is used for actual style purposes. This should be either standardized (so future animations would behave the same) or removed and standardized on a per-child-theme basis if necessary. I'd choose option 1 for now, until we decide we want transitions throughout the theme (if we will).

**Comment by luukdv** [comment] 2016-05-10 10:54
Agreed, we should use grid for this. Our most recent projects are using this for galleries as well, maybe you can copy something from there.

**Comment by sboerrigter** [comment] 2016-05-12 11:43
> There seem to be four items next to eachother (opposed to the 6 in the screenshot)
Five items would fit too, that would probably look better (using the grid would eliminate the need of a lot of code)

The number of items depends on your thumbnail size setting. If you use the TrendPress default thumbnail size (120x120), there are six items next to each other on desktops. See:

![screen shot 2016-05-12 at 13 38 47](https://cloud.githubusercontent.com/assets/786875/15213344/e42976f8-1846-11e6-8e6a-6cddd8498b97.png)

> Responsive is not that beautiful (using grid would make it better)

I tried using grid for this, but I don't like the effect that all images are scaled down. On many screen sizes the images become too small in my opinion. We could make the images bigger, but this would increase the file size and loading time.

> When fitting five items, they don't fit by 10px. Using the grid would allow you to always fill the width of the content.

This is probably caused by your thumbnail size as well.

> Transition should probably be removed, since this would be the only instance in the entire theme where transition is used for actual style purposes. This should be either standardized (so future animations would behave the same) or removed and standardized on a per-child-theme basis if necessary. I'd choose option 1 for now, until we decide we want transitions throughout the theme (if we will).

Removed the transition (for now).

**Closed** 2016-05-12 13:34 UTC
Labels: enhancement
