### ISSUE TITLE
Minify without `.min`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#550] opened 2015-09-04 10:41 UTC
This should be investigated. Somehow, source maps don't work when _not_ renaming the minified file.

**Comment by sboerrigter** [comment] 2015-10-02 13:55
I removed the `.min` part from the compiled CSS files, and the source maps seem to work just fine. I can't reproduce your problem. Can sombody else test this?

**Comment by haroldangenent** [comment] 2015-10-02 14:40
They still have the same issues. Look at my screenshot for an example. Main.css is not a source file (and only has one line).

![schermafbeelding 2015-10-02 om 16 35 40](https://cloud.githubusercontent.com/assets/1481468/10249179/3506e9ac-6924-11e5-94fa-4e55ab2ae0aa.png)

**Comment by sboerrigter** [comment] 2015-10-02 15:25
I have reverted my changes, but this doesn't seem to have fixed the issue.

![screen shot 2015-10-02 at 17 24 54](https://cloud.githubusercontent.com/assets/786875/10250359/8bd342de-692a-11e5-815d-906d03e2a2fb.png)

**Comment by haroldangenent** [comment] 2015-10-02 15:28
Seems to work way better. Getting this out of this release for now.

![schermafbeelding 2015-10-02 om 17 28 22](https://cloud.githubusercontent.com/assets/1481468/10250427/047a7da6-692b-11e5-8dc1-427a1255f3cd.png)

**Comment by luukdv** [comment] 2016-02-08 13:17
Shall we close this one after #577?

**Comment by gewoonderrik** [comment] 2016-02-18 14:36
#577 has been resolved. I'm closing this issue.

**Comment by gewoonderrik** [comment] 2016-02-18 15:45
Wait. I'm confused. Does this still belong in the milestone?

**Comment by haroldangenent** [comment] 2016-02-18 15:48
Yes.

**Closed** 2016-02-19 08:50 UTC
Labels: enhancement, needs-research
