### ISSUE TITLE
Title/description clears mobile toggle buttons

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#410] opened 2015-04-17 12:55 UTC
The outer right of the search field also doesn't align with the menu toggle button.

![screenshot 2015-04-17 14 54 42](https://cloud.githubusercontent.com/assets/1583229/7202335/af46de4e-e511-11e4-8323-023c166bf135.png)

**Comment by luukdv** [comment] 2015-04-17 13:14
The description of the issue is now fixed, not the issue title. From 400px the title and buttons will clear, but your subtitle is pretty long. Things like that should be adjusted for specific themes I think. Do you agree?

**Comment by haroldangenent** [comment] 2015-04-17 13:23
Works perfectly, in my opinion. @gewoonderrik?

**Closed** 2015-04-17 13:34 UTC
Labels: bug
