### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#615] opened 2016-03-17 17:14 UTC
- Alignment + margins on archive
- Alignment like `alignright` images on single

**Comment by sboerrigter** [comment] 2016-03-17 18:07
I allready fixed this. Shall I close this?

**Comment by luukdv** [comment] 2016-03-17 18:07
No, let's put it in the next milestone.

**Comment by haroldangenent** [comment] 2016-03-18 10:02
> - Alignment like alignright images on single

This doesn't seem fixed yet. Or don't you agree @sboerrigter?

Why do the featured images have margin on the top? Is this because of the line-height? Because I'd rather calculate this, so it would also be right when using another line-height or font-size.

Also, the margin-bottom seems kind of large on smaller screens.

**Comment by sboerrigter** [comment] 2016-04-28 15:42
> This doesn't seem fixed yet. Or don't you agree @sboerrigter?
It works fine over here. Do you have an example where it doesn't work properly?

> Why do the featured images have margin on the top? Is this because of the line-height? Because I'd rather calculate this, so it would also be right when using another line-height or font-size.
Yes, that is to align it with the text. I think calculating this should be a new issue for another milestone.

> Also, the margin-bottom seems kind of large on smaller screens.
I don't think it's too large. Can you make a screenshot of what you mean?

**Comment by haroldangenent** [comment] 2016-05-03 14:29
> It works fine over here. Do you have an example where it doesn't work properly?
Any featured image on a post doesn't break to the right, as `alignright` does. This issue describes that it should. (For example, /2013/01/10/markup-image-alignment/ when using Automattic's unit test data).

> Yes, that is to align it with the text. I think calculating this should be a new issue for another milestone.
Okay #659.

> I don't think it's too large. Can you make a screenshot of what you mean?
Not sure what I meant either.

**Comment by sboerrigter** [comment] 2016-05-12 11:59
Can't reproduce. Can you show me IRL?

![screen shot 2016-05-12 at 13 58 57](https://cloud.githubusercontent.com/assets/786875/15213798/b1266cfe-1849-11e6-8d6c-bcb6aef5d0dd.png)

**Closed** 2016-05-12 13:47 UTC
Labels: enhancement, needs-testing
